name: Galleon Pack Template Java CI

on: [push, pull_request]

jobs:
  # This just runs mvn install like a user would on cloning the repository
  raw:
    name: Normal checkout

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and Test
        run: |
          mvn --version
          mvn -B install

      - name: Zip Artifacts
        run: zip -R artifacts.zip 'server.log' 'surefire-reports/*.txt' 'surefire-reports/*.xml'

      - uses: actions/upload-artifact@v1
        with:
          # Expressions in the name don't seem to get resolved
          #name: ci-artifacts-galleon-template-raw-{{job.container.id}}
          name: ci-artifacts-galleon-template-raw
          path: artifacts.zip


  wildfly-master:
    # This adjusts the build to use the versions from wildfly master
    name: Against WildFly master

    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature pack
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout wildfly master
        uses: actions/checkout@v2
        with:
          repository: wildfly/wildfly
          path: wildfly-master

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Initialise Feature Pack version
        # Needed to download everything from Maven to not pollute the output in the next steps
        run:
          mvn help:evaluate -Dexpression=project.version -pl .
        working-directory: main

      - name: Set FEATURE_PACK_VERSION
        run: |
          TMP="$(mvn help:evaluate -Dexpression=project.version -pl . | grep -v '^\[')"
          echo "::set-env name=FEATURE_PACK_VERSION::${TMP}" ;
          echo "TMP ${TMP}"
        working-directory: main

      - name: Initialise WildFly versions
        # Needed to download everything from Maven to not pollute the output in the next steps
        run: |
          mvn -B help:evaluate -Dexpression=project.version -pl .
          mvn -B help:evaluate -Dexpression=version.org.wildfly.core -pl .
        working-directory: wildfly-master

      - name: Set WILDFLY_VERSION
        run: |
          TMP="$(mvn help:evaluate -Dexpression=project.version -pl . | grep -v '^\[')"
          echo "::set-env name=WILDFLY_VERSION::${TMP}"
        working-directory: wildfly-master

      - name: Set WILDFLY_CORE_VERSION
        run: |
          TMP="$(mvn help:evaluate -Dexpression=version.org.wildfly.core -pl . | grep -v '^\[')"
          echo "::set-env name=WILDFLY_CORE_VERSION::${TMP}"
        working-directory: wildfly-master

      - name: Show read versions
        run: |
          echo "Feature pack version ${FEATURE_PACK_VERSION}"
          echo "WildFly version ${WILDFLY_VERSION}"
          echo "WildFly Core version ${WILDFLY_CORE_VERSION}"

      - name: Build WildFly master
        run: mvn -B install -DskipTests
        working-directory: wildfly-master

      - name: Build and Test
        run: |
          mvn --version
          mvn -B install -Dversion.org.wildfly=${WILDFLY_VERSION} -Dversion.org.wildfly.core=${WILDFLY_CORE_VERSION}
        working-directory: main

      - name: Calculate directories to check
        run: |
          SRV_DIR="build/target/wildfly-${WILDFLY_VERSION}-template-${FEATURE_PACK_VERSION}"
          echo "::set-env name=BUILD_SERVER_DIR::${SRV_DIR}"
          MODULES_BASE="${SRV_DIR}/modules/system/layers/base"
          echo "::set-env name=UNDERTOW_MODULE_XML::${MODULES_BASE}/org/wildfly/extension/undertow/main/module.xml"
          echo "::set-env name=CONTROLLER_MODULE_XML::${MODULES_BASE}/org/jboss/as/controller/main/module.xml"

      - name: Check versions
        run: |
          if grep -q org.wildfly:wildfly-undertow:${WILDFLY_VERSION} "${UNDERTOW_MODULE_XML}" && grep -q org.wildfly.core:wildfly-controller:${WILDFLY_CORE_VERSION} "${CONTROLLER_MODULE_XML}"; then
            echo "Versions in module.xml files as expected!"
          else
            echo "Versions in module.xml files not as expected!"
            "Expected WildFly version '${WILDFLY_VERSION}' and Core version '${WILDFLY_CORE_VERSION}'"
            echo "Showing contents of ${UNDERTOW_MODULE_XML} and ${CONTROLLER_MODULE_XML}"
            echo "Exiting..."
            exit 1
          fi
        working-directory: main

      - name: Zip Artifacts
        run: zip -R artifacts.zip 'server.log' 'surefire-reports/*.txt' 'surefire-reports/*.xml'
        working-directory: main

      - uses: actions/upload-artifact@v1
        with:
          # Expressions in the name don't seem to get resolved
          #name: ci-artifacts-galleon-template-wf-master-{{job.container.id}}
          name: ci-artifacts-galleon-template-wf-master
          path: main/artifacts.zip